<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>poligon_pezeglądarka_grafiki</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>img\73042biohazard_109537(1).ico</ApplicationIcon>
	  <AssemblyVersion>1.0.*</AssemblyVersion>
	  <FileVersion>1.0.*</FileVersion>
	  <Deterministic>false</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Config\default.ini" />
    <None Remove="Img\00041-3739771558.jpg" />
    <None Remove="Img\g1.png" />
  </ItemGroup>

	<!--ItemGroup>
		<AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
			<_Parameter1>BuildDateTime</_Parameter1>
			<_Parameter2>$([System.DateTime]::UtcNow.ToString("yyyy-MM-dd HH:mm:ss"))</_Parameter2>
		</AssemblyAttribute>

	</ItemGroup-->
	
  <ItemGroup>
    <EmbeddedResource Include="Img\73042biohazard_109537%281%29.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <Content Include="Config\default.ini">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Resource Include="Img\00041-3739771558.jpg" />
    <Resource Include="Img\g1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="gong-wpf-dragdrop" Version="4.0.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Exceptions\" />
    <Folder Include="Style\" />
  </ItemGroup>
	<ItemGroup>
		<Resource Include="Img\73042biohazard_109537(1).ico">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>
	
</Project>
